DROP TABLE TSHOP.TB_COMMENT_INFO;
DROP TABLE TSHOP.TB_INTEREST_ITEM;
DROP TABLE TSHOP.TB_POST_IMAGEFILE;
DROP TABLE TSHOP.TB_POST_INFO;
DROP TABLE TSHOP.TB_USER_ORDER_DETAIL;
DROP TABLE TSHOP.TB_USER_ORDER;
DROP TABLE TSHOP.TB_BOARD_INFO;
DROP TABLE TSHOP.TB_PRODUCT_IMAGEFILE;
DROP TABLE TSHOP.TB_PRODUCT_INFO;
DROP TABLE TSHOP.TB_USER_INFO;

-- 1. TB_USER_INFO 테이블
CREATE TABLE TSHOP.TB_USER_INFO(
	  USER_ID VARCHAR(20) NOT NULL
	, USER_PW VARCHAR(20) NOT NULL
	, USER_NAME VARCHAR(20) NULL
	, USER_GENDER VARCHAR(20) NULL -- 1:남성 2:여성
	, USER_DOB VARCHAR(20) NULL
	, USER_ADDRESS1 VARCHAR(20) NULL -- 우편번호
	, USER_ADDRESS2 VARCHAR(20) NULL -- 기본주소
	, USER_ADDRESS3 VARCHAR(20) NULL -- 상세주소
	, USER_PHONE VARCHAR(20) NULL
	, USER_EMAIL VARCHAR(20) NULL
	, USER_AUTHORITY VARCHAR(20) NULL	-- 0:관리자 1:유저
	, USER_STATE VARCHAR(20) NULL -- 0:탈퇴 1:활동중 2:정지
	, USER_REGISTER_DT DATE NULL
	, USER_UPDATE_DT DATE NULL
);
ALTER TABLE TSHOP.TB_USER_INFO ADD CONSTRAINT PK_TB_USER_INFO PRIMARY KEY (USER_ID);

-- 2. BOARD 테이블
CREATE TABLE TSHOP.TB_BOARD_INFO (
	  BOARD_NUMBER            NUMBER          NOT NULL
	, BOARD_NAME              VARCHAR(20)     NULL
	, BOARD_INPUT_DATE        DATE DEFAULT SYSDATE NULL
	, BOARD_CORRECT           DATE            NULL
	, BOARD_DELETE_DATE       DATE            NULL
);
ALTER TABLE TSHOP.TB_BOARD_INFO ADD CONSTRAINT PK_TB_BOARD_INFO PRIMARY KEY (BOARD_NUMBER);

-- 3. POST 테이블
CREATE TABLE TSHOP.TB_POST_INFO (
	POST_NUMBER             NUMBER          NOT NULL,
	BOARD_NUMBER            NUMBER          NOT NULL,
	POST_TITLE              VARCHAR(100)    NOT NULL,
	POST_CONTENTS           VARCHAR(1000)   NOT NULL,
	POST_CATEGORY           NUMBER          NOT NULL, -- 1: 마우스 2:키보드
	POST_SCORE              NUMBER          NOT NULL,
	POST_INPUT_DATE         DATE DEFAULT SYSDATE NOT NULL,
	POST_CORRECT            DATE            NULL,
	POST_DELETE_DATE        DATE            NULL,
	POST_RECOMMEND          NUMBER DEFAULT 0 NOT NULL,
	USER_ID                 VARCHAR(20)     NOT NULL
);
ALTER TABLE TSHOP.TB_POST_INFO ADD CONSTRAINT PK_TB_POST PRIMARY KEY (POST_NUMBER);
COMMENT ON COLUMN TSHOP.TB_POST_INFO.POST_CATEGORY IS '1: 마우스 2:키보드';

-- 4. TB_COMMENT 테이블
CREATE TABLE TSHOP.TB_COMMENT_INFO (
	COMMENT_NUMBER          NUMBER          NOT NULL,
	POST_NUMBER             NUMBER          NOT NULL,
	BOARD_NUMBER            NUMBER          NOT NULL,
	COMMENT_CONTENTS        VARCHAR(1000)   NOT NULL,
	COMMENT_INPUT_DATE      DATE DEFAULT SYSDATE NOT NULL,
	COMMENT_CORRECT         DATE            NULL,
	COMMENT_DELETE_DATE     DATE            NULL,
	COMMENT_RECOMMEND       NUMBER DEFAULT 0 NOT NULL,
	USER_ID                 VARCHAR(20)     NOT NULL
);
ALTER TABLE TSHOP.TB_COMMENT_INFO ADD CONSTRAINT PK_TB_COMMENT PRIMARY KEY (COMMENT_NUMBER, POST_NUMBER, BOARD_NUMBER);

-- 5. PRODUCT 테이블
CREATE TABLE TSHOP.TB_PRODUCT_INFO (
	PRODUCT_NUMBER          NUMBER          NOT NULL,
	PRODUCT_CATEGORY        VARCHAR(100)     NOT NULL,
	PRODUCT_STATE           NUMBER          NOT NULL, -- 0:준비중 1:판매중
	PRODUCT_NAME            VARCHAR(100)     NOT NULL,
	PRODUCT_PRICE           NUMBER          NOT NULL,
	PRODUCT_STOCK           NUMBER          NULL,
	PRODUCT_DESC            VARCHAR(2000)   NOT NULL,
	PRODUCT_HITS            NUMBER DEFAULT 0 NOT NULL,
	PRODUCT_DATE            DATE DEFAULT SYSDATE NOT NULL,
	PRODUCT_CORRECT         DATE            NULL,
	PRODUCT_DELETE_DATE     DATE            NULL,
	USER_ID                 VARCHAR(20)     NOT NULL
);
ALTER TABLE TSHOP.TB_PRODUCT_INFO ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_NUMBER);
COMMENT ON COLUMN TSHOP.TB_PRODUCT_INFO.PRODUCT_STATE IS '0:준비중 1:판매중';

-- 6. TB_USER_ORDER 테이블
CREATE TABLE TSHOP.TB_USER_ORDER (
	ORDER_NUMBER            NUMBER          NOT NULL,
	ORDER_DATE              DATE DEFAULT SYSDATE NOT NULL,
	DELIVERY_ADDRESS1       VARCHAR(20)     NOT NULL,
	DELIVERY_ADDRESS2       VARCHAR(20)     NOT NULL,
	DELIVERY_ADDRESS3       VARCHAR(20)     NOT NULL,
	DELIVERY_MESSAGE        VARCHAR(100)    NULL,
	RECEIVER_NAME           VARCHAR(20)     NOT NULL,
	RECEIVER_PHONE          VARCHAR(20)     NOT NULL,
	USER_ID                 VARCHAR(20)     NOT NULL
);
ALTER TABLE TSHOP.TB_USER_ORDER ADD CONSTRAINT PK_TB_USER_ORDER PRIMARY KEY (ORDER_NUMBER);

-- 7. TB_USER_ORDER_DETAIL 테이블
CREATE TABLE TSHOP.TB_USER_ORDER_DETAIL (
	ORDER_DETAIL_NUMBER     NUMBER          NOT NULL,
	ORDER_COUNT             NUMBER          NULL,
	ORDER_STATE             NUMBER          NULL,
	ORDER_NUMBER            NUMBER          NOT NULL,
	PRODUCT_NUMBER          NUMBER          NOT NULL
);
ALTER TABLE TSHOP.TB_USER_ORDER_DETAIL ADD CONSTRAINT PK_TB_USER_ORDER_DETAIL PRIMARY KEY (ORDER_DETAIL_NUMBER);

-- 8. INTEREST_ITEM 테이블
CREATE TABLE TSHOP.TB_INTEREST_ITEM (
	INTEREST_ITEMNUMBER     NUMBER          NOT NULL,
	USER_ID                 VARCHAR(20)     NOT NULL,
	PRODUCT_NUMBER          NUMBER          NOT NULL
	, DELETE_YN VARCHAR(20) NULL
	, REGISTER_DT DATE NULL
	, UPDATE_DT DATE NULL
);
ALTER TABLE TSHOP.TB_INTEREST_ITEM ADD CONSTRAINT PK_TB_INTEREST_ITEM PRIMARY KEY (INTEREST_ITEMNUMBER, USER_ID);

-- 9. TB_PRODUCT_IMAGEFILE 테이블 (BOARD_NUMBER 추가됨)
CREATE TABLE TSHOP.TB_PRODUCT_IMAGEFILE (
	ATTACH_NUMBER                       NUMBER         NOT NULL,
	ATTACH_THUMBNAIL_ORIGINAL_NAME     VARCHAR(200)    NULL,
	ATTACH_THUMBNAIL_SAVE_NAME         VARCHAR(200)    NULL,
	ATTACH_THUMBNAIL_SIZE              NUMBER          NULL,
	ATTACH_THUMBNAIL_LOCATION          VARCHAR(200)    NULL,
	ATTACH_CONTENTS_ORIGINAL_NAME      VARCHAR(200)    NULL,
	ATTACH_CONTENTS_SAVE_NAME          VARCHAR(200)    NULL,
	ATTACH_CONTENTS_SIZE               NUMBER          NULL,
	ATTACH_CONTENTS_LOCATION           VARCHAR(200)    NULL,
	ATTACH_INSERT_DATE                 DATE            NULL,
	ATTACH_DELETE_DATE                 DATE            NULL,
	PRODUCT_NUMBER                     NUMBER          NOT NULL
);
ALTER TABLE TSHOP.TB_PRODUCT_IMAGEFILE ADD CONSTRAINT PK_TB_PRODUCT_IMAGEFILE PRIMARY KEY (ATTACH_NUMBER);

-- 10. TB_POST_IMAGEFILE 테이블 (BOARD_NUMBER 추가됨)
CREATE TABLE TSHOP.TB_POST_IMAGEFILE (
	ATTACH_NUMBER                       NUMBER          NOT NULL,
	ATTACH_THUMBNAIL_ORIGINAL_NAME     VARCHAR(200)     NULL,
	ATTACH_THUMBNAIL_SAVE_NAME         VARCHAR(200)     NULL,
	ATTACH_THUMBNAIL_SIZE              NUMBER           NULL,
	ATTACH_THUMBNAIL_LOCATION          VARCHAR(200)     NULL,
	ATTACH_CONTENTS_ORIGINAL_NAME      VARCHAR(200)     NULL,
	ATTACH_CONTENTS_SAVE_NAME          VARCHAR(200)     NULL,
	ATTACH_CONTENTS_SIZE               NUMBER           NULL,
	ATTACH_CONTENTS_LOCATION           VARCHAR(200)     NULL,
	ATTACH_INSERT_DATE                 DATE             NULL,
	ATTACH_DELETE_DATE                 DATE             NULL,
	POST_NUMBER                     NUMBER          NOT NULL
);
ALTER TABLE TSHOP.TB_POST_IMAGEFILE ADD CONSTRAINT PK_TB_POST_IMAGEFILE PRIMARY KEY (ATTACH_NUMBER);
-- =============================================
-- 외래키 제약조건 설정
-- =============================================
-- POST
ALTER TABLE TSHOP.TB_POST_INFO ADD CONSTRAINT FK_BOARD_TO_POST_1 
FOREIGN KEY (BOARD_NUMBER) REFERENCES TSHOP.TB_BOARD_INFO (BOARD_NUMBER);

ALTER TABLE TSHOP.TB_POST_INFO ADD CONSTRAINT FK_USER_TO_POST_1 
FOREIGN KEY (USER_ID) REFERENCES TSHOP.TB_USER_INFO(USER_ID);
-- TB_COMMENT
ALTER TABLE TSHOP.TB_COMMENT_INFO ADD CONSTRAINT FK_POST_TO_COMMENT 
FOREIGN KEY (POST_NUMBER) 
REFERENCES TSHOP.TB_POST_INFO (POST_NUMBER);

ALTER TABLE TSHOP.TB_COMMENT_INFO ADD CONSTRAINT FK_USER_TO_COMMENT_1 
FOREIGN KEY (USER_ID) REFERENCES TSHOP.TB_USER_INFO(USER_ID);
-- TB_USER_ORDER
ALTER TABLE TSHOP.TB_USER_ORDER ADD CONSTRAINT FK_USER_TO_USER_ORDER_1 
FOREIGN KEY (USER_ID) REFERENCES TSHOP.TB_USER_INFO(USER_ID);
-- TB_USER_ORDER_DETAIL
ALTER TABLE TSHOP.TB_USER_ORDER_DETAIL ADD CONSTRAINT FK_USER_ORDER_TO_USERORDER_DETAIL_1 
FOREIGN KEY (ORDER_NUMBER) REFERENCES TSHOP.TB_USER_ORDER (ORDER_NUMBER);

ALTER TABLE TSHOP.TB_USER_ORDER_DETAIL ADD CONSTRAINT FK_PRODUCT_TO_USERORDER_DETAIL_1 
FOREIGN KEY (PRODUCT_NUMBER) REFERENCES TSHOP.TB_PRODUCT_INFO (PRODUCT_NUMBER);
-- PRODUCT
ALTER TABLE TSHOP.TB_PRODUCT_INFO ADD CONSTRAINT FK_USER_TO_PRODUCT_1 
FOREIGN KEY (USER_ID) REFERENCES TSHOP.TB_USER_INFO(USER_ID);
-- INTEREST_ITEM
ALTER TABLE TSHOP.TB_INTEREST_ITEM ADD CONSTRAINT FK_USER_TO_INTEREST_ITEM_1 
FOREIGN KEY (USER_ID) REFERENCES TSHOP.TB_USER_INFO(USER_ID);

ALTER TABLE TSHOP.TB_INTEREST_ITEM ADD CONSTRAINT FK_PRODUCT_TO_INTEREST_ITEM_1 
FOREIGN KEY (PRODUCT_NUMBER) REFERENCES TSHOP.TB_PRODUCT_INFO (PRODUCT_NUMBER);
ALTER USER TSHOP QUOTA UNLIMITED ON USERS;
-- TB_PRODUCT_IMAGEFILE
ALTER TABLE TSHOP.TB_PRODUCT_IMAGEFILE ADD CONSTRAINT FK_PRODUCT_TO_TB_PRODUCT_IMAGEFILE_1 
FOREIGN KEY (PRODUCT_NUMBER) REFERENCES TSHOP.TB_PRODUCT_INFO (PRODUCT_NUMBER);

-- TB_PRODUCT_IMAGEFILE
ALTER TABLE TSHOP.TB_POST_IMAGEFILE ADD CONSTRAINT FK_POST_TO_TB_POST_IMAGEFILE_1 
FOREIGN KEY (POST_NUMBER) REFERENCES TSHOP.TB_POST_INFO (POST_NUMBER);

--유저 샘플 데이터삽입
INSERT INTO TSHOP.TB_USER_INFO(
	  USER_ID
	, USER_PW
	, USER_NAME
	, USER_GENDER
	, USER_DOB
	, USER_ADDRESS1
	, USER_ADDRESS2
	, USER_ADDRESS3
	, USER_PHONE
	, USER_EMAIL
	, USER_AUTHORITY
	, USER_STATE
	, USER_REGISTER_DT
	, USER_UPDATE_DT
)
VALUES(
	  'kimmjk3'
	, 'qwer1234'
	, '김이름'
	, 1
	, '20000101'
	, '123-456'
	, '상세주소'
	, '도로명주소'
	, '010-1234-5678'
	, 'kimmjk3@gmail.com'
	, 0
	, 1 
	, SYSDATE
	, NULL
);

--게시판 샘플 데이터삽입
INSERT INTO TSHOP.TB_BOARD_INFO(
	  BOARD_NUMBER
	, BOARD_NAME
	, BOARD_INPUT_DATE
	, BOARD_CORRECT
	, BOARD_DELETE_DATE
)
VALUES(
	  CASE WHEN (SELECT MAX(BOARD_NUMBER) FROM TSHOP.TB_BOARD_INFO) IS NULL THEN 1 ELSE (SELECT MAX(BOARD_NUMBER) + 1 FROM TSHOP.TB_BOARD_INFO) END
	, '리뷰'
	, SYSDATE
	, NULL
	, NULL
)
;

INSERT INTO TSHOP.TB_POST_INFO(
	  POST_NUMBER
	, BOARD_NUMBER
	, POST_TITLE
	, POST_CONTENTS
	, POST_CATEGORY
	, POST_SCORE
	, POST_INPUT_DATE
	, POST_CORRECT
	, POST_DELETE_DATE
	, POST_RECOMMEND
	, USER_ID
)
VALUES(
	  CASE WHEN (SELECT MAX(POST_NUMBER) FROM TSHOP.TB_POST_INFO) IS NULL THEN 1 ELSE (SELECT MAX(POST_NUMBER) + 1 FROM TSHOP.TB_POST_INFO) END
	, 1
	, '첫번째 리뷰 샘플'
	, '첫번재 리뷰 내용'
	, 1
	, 5
	, SYSDATE 
	, NULL
	, NULL
	, 1
	, 'kimmjk3'
);
INSERT INTO TSHOP.TB_POST_INFO(
	  POST_NUMBER
	, BOARD_NUMBER
	, POST_TITLE
	, POST_CONTENTS
	, POST_CATEGORY
	, POST_SCORE
	, POST_INPUT_DATE
	, POST_CORRECT
	, POST_DELETE_DATE
	, POST_RECOMMEND
	, USER_ID
)
VALUES(
	  CASE WHEN (SELECT MAX(POST_NUMBER) FROM TSHOP.TB_POST_INFO) IS NULL THEN 1 ELSE (SELECT MAX(POST_NUMBER) + 1 FROM TSHOP.TB_POST_INFO) END
	, 1
	, '두번째 리뷰 샘플'
	, '두번째 리뷰 내용'
	, 1
	, 5
	, SYSDATE 
	, NULL
	, NULL
	, 1
	, 'kimmjk3'
);
INSERT INTO TSHOP.TB_POST_INFO(
	  POST_NUMBER
	, BOARD_NUMBER
	, POST_TITLE
	, POST_CONTENTS
	, POST_CATEGORY
	, POST_SCORE
	, POST_INPUT_DATE
	, POST_CORRECT
	, POST_DELETE_DATE
	, POST_RECOMMEND
	, USER_ID
)
VALUES(
	  CASE WHEN (SELECT MAX(POST_NUMBER) FROM TSHOP.TB_POST_INFO) IS NULL THEN 1 ELSE (SELECT MAX(POST_NUMBER) + 1 FROM TSHOP.TB_POST_INFO) END
	, 1
	, '세번째 리뷰 샘플'
	, '세번째 리뷰 내용'
	, 1
	, 5
	, SYSDATE 
	, NULL
	, NULL
	, 1
	, 'kimmjk3'
);

--상품 데이터삽입
INSERT INTO TSHOP.TB_PRODUCT_INFO(
	  PRODUCT_NUMBER
	, PRODUCT_CATEGORY
	, PRODUCT_STATE
	, PRODUCT_NAME
	, PRODUCT_PRICE
	, PRODUCT_STOCK
	, PRODUCT_DESC
	, PRODUCT_HITS
	, PRODUCT_DATE
	, PRODUCT_CORRECT
	, PRODUCT_DELETE_DATE
	, USER_ID
)
VALUES(
	  CASE WHEN (SELECT MAX(PRODUCT_NUMBER) FROM TSHOP.TB_PRODUCT_INFO) IS NULL THEN 1 ELSE (SELECT MAX(PRODUCT_NUMBER) + 1 FROM TSHOP.TB_PRODUCT_INFO) END
	, '1'
	, '2'
	, '타이폰 마르스프로 기계식 키보드 mk3'
	, '172500'
	, 50
	, '타이폰 마르스프로 기계식 키보드 mk3'
	, 0 
	, SYSDATE
	, NULL
	, NULL
	, 'kimmjk3'
);
INSERT INTO TSHOP.TB_PRODUCT_INFO(
	  PRODUCT_NUMBER
	, PRODUCT_CATEGORY
	, PRODUCT_STATE
	, PRODUCT_NAME
	, PRODUCT_PRICE
	, PRODUCT_STOCK
	, PRODUCT_DESC
	, PRODUCT_HITS
	, PRODUCT_DATE
	, PRODUCT_CORRECT
	, PRODUCT_DELETE_DATE
	, USER_ID
)
VALUES(
	  CASE WHEN (SELECT MAX(PRODUCT_NUMBER) FROM TSHOP.TB_PRODUCT_INFO) IS NULL THEN 1 ELSE (SELECT MAX(PRODUCT_NUMBER) + 1 FROM TSHOP.TB_PRODUCT_INFO) END
	, '1'
	, '2'
	, '풀튜닝 타이폰 마르스프로 슈팅스타 기계식 키보드'
	, '185000'
	, 40
	, '풀튜닝 타이폰 마르스프로 슈팅스타 기계식 키보드'
	, 0 
	, SYSDATE
	, NULL
	, NULL
	, 'kimmjk3'
);

INSERT INTO TSHOP.TB_PRODUCT_INFO(
	  PRODUCT_NUMBER
	, PRODUCT_CATEGORY
	, PRODUCT_STATE
	, PRODUCT_NAME
	, PRODUCT_PRICE
	, PRODUCT_STOCK
	, PRODUCT_DESC
	, PRODUCT_HITS
	, PRODUCT_DATE
	, PRODUCT_CORRECT
	, PRODUCT_DELETE_DATE
	, USER_ID
)
VALUES(
	  CASE WHEN (SELECT MAX(PRODUCT_NUMBER) FROM TSHOP.TB_PRODUCT_INFO) IS NULL THEN 1 ELSE (SELECT MAX(PRODUCT_NUMBER) + 1 FROM TSHOP.TB_PRODUCT_INFO) END
	, '1'
	, '2'
	, '풀튜닝 타이폰 마르스프로 베스타 기계식 키보드'
	, '197000'
	, 35
	, '풀튜닝 타이폰 마르스프로 베스타 기계식 키보드'
	, 0 
	, SYSDATE
	, NULL
	, NULL
	, 'kimmjk3'
);

--상품 이미지 첨부
INSERT INTO TSHOP.TB_PRODUCT_IMAGEFILE(
	  ATTACH_NUMBER                      	
	, ATTACH_THUMBNAIL_ORIGINAL_NAME     	
	, ATTACH_THUMBNAIL_SAVE_NAME         	
	, ATTACH_THUMBNAIL_SIZE              	
	, ATTACH_THUMBNAIL_LOCATION          	
	, ATTACH_CONTENTS_ORIGINAL_NAME      	
	, ATTACH_CONTENTS_SAVE_NAME          	
	, ATTACH_CONTENTS_SIZE               	
	, ATTACH_CONTENTS_LOCATION           	
	, ATTACH_INSERT_DATE                 	
	, ATTACH_DELETE_DATE                 	
	, PRODUCT_NUMBER                     	
)
VALUES(
	  CASE WHEN (SELECT MAX(ATTACH_NUMBER) FROM TSHOP.TB_PRODUCT_IMAGEFILE) IS NULL THEN 1 ELSE (SELECT MAX(ATTACH_NUMBER) + 1 FROM TSHOP.TB_PRODUCT_IMAGEFILE) END
	, '원썸1.jpg'
	, '샘플썸네일1.jpg'
	, 500
	, '/attach/샘플썸네일1.jpg'
	, '원내1'
	, '샘플내용1'
	, 500
	, '/attach/샘플내용1.jpg'
	, SYSDATE
	, SYSDATE
	, 1
);

--상품 이미지 첨부
INSERT INTO TSHOP.TB_PRODUCT_IMAGEFILE(
	  ATTACH_NUMBER                      	
	, ATTACH_THUMBNAIL_ORIGINAL_NAME     	
	, ATTACH_THUMBNAIL_SAVE_NAME         	
	, ATTACH_THUMBNAIL_SIZE              	
	, ATTACH_THUMBNAIL_LOCATION          	
	, ATTACH_CONTENTS_ORIGINAL_NAME      	
	, ATTACH_CONTENTS_SAVE_NAME          	
	, ATTACH_CONTENTS_SIZE               	
	, ATTACH_CONTENTS_LOCATION           	
	, ATTACH_INSERT_DATE                 	
	, ATTACH_DELETE_DATE                 	
	, PRODUCT_NUMBER                     	
)
VALUES(
	  CASE WHEN (SELECT MAX(ATTACH_NUMBER) FROM TSHOP.TB_PRODUCT_IMAGEFILE) IS NULL THEN 1 ELSE (SELECT MAX(ATTACH_NUMBER) + 1 FROM TSHOP.TB_PRODUCT_IMAGEFILE) END
	, '원썸2.jpg'
	, '샘플썸네일2.jpg'
	, 500
	, '/attach/샘플썸네일2.jpg'
	, '원내2'
	, '샘플내용2'
	, 500
	, '/attach/샘플내용2.jpg'
	, SYSDATE
	, SYSDATE
	, 2
);

--상품 이미지 첨부
INSERT INTO TSHOP.TB_PRODUCT_IMAGEFILE(
	  ATTACH_NUMBER                      	
	, ATTACH_THUMBNAIL_ORIGINAL_NAME     	
	, ATTACH_THUMBNAIL_SAVE_NAME         	
	, ATTACH_THUMBNAIL_SIZE              	
	, ATTACH_THUMBNAIL_LOCATION          	
	, ATTACH_CONTENTS_ORIGINAL_NAME      	
	, ATTACH_CONTENTS_SAVE_NAME          	
	, ATTACH_CONTENTS_SIZE               	
	, ATTACH_CONTENTS_LOCATION           	
	, ATTACH_INSERT_DATE                 	
	, ATTACH_DELETE_DATE                 	
	, PRODUCT_NUMBER                     	
)
VALUES(
	  CASE WHEN (SELECT MAX(ATTACH_NUMBER) FROM TSHOP.TB_PRODUCT_IMAGEFILE) IS NULL THEN 1 ELSE (SELECT MAX(ATTACH_NUMBER) + 1 FROM TSHOP.TB_PRODUCT_IMAGEFILE) END
	, '원썸3.jpg'
	, '샘플썸네일3.jpg'
	, 500
	, '/attach/샘플썸네일2.jpg'
	, '원내3'
	, '샘플내용3'
	, 500
	, '/attach/샘플내용3.jpg'
	, SYSDATE
	, SYSDATE
	, 3
);

-- 게시글 이미지 첨부
INSERT INTO TSHOP.TB_POST_IMAGEFILE(
	  ATTACH_NUMBER
	, ATTACH_THUMBNAIL_ORIGINAL_NAME
	, ATTACH_THUMBNAIL_SAVE_NAME
	, ATTACH_THUMBNAIL_SIZE
	, ATTACH_THUMBNAIL_LOCATION
	, ATTACH_CONTENTS_ORIGINAL_NAME
	, ATTACH_CONTENTS_SAVE_NAME
	, ATTACH_CONTENTS_SIZE
	, ATTACH_CONTENTS_LOCATION
	, ATTACH_INSERT_DATE
	, ATTACH_DELETE_DATE
	, POST_NUMBER
)
VALUES(
	  CASE WHEN (SELECT MAX(ATTACH_NUMBER) FROM TSHOP.TB_POST_IMAGEFILE) IS NULL THEN 1 ELSE (SELECT MAX(ATTACH_NUMBER) + 1 FROM TSHOP.TB_POST_IMAGEFILE) END
	, '리샘1.jpg'
	, '리뷰샘플1.jpg'
	, 500
	, '/attach/리뷰샘플1.jpg'
	, '리샘1-1'
	, '리뷰샘플1-2'
	, 500
	, '/attach/리뷰샘플1-2'
	, SYSDATE
	, SYSDATE
	, 1
);
INSERT INTO TSHOP.TB_POST_IMAGEFILE(
	  ATTACH_NUMBER
	, ATTACH_THUMBNAIL_ORIGINAL_NAME
	, ATTACH_THUMBNAIL_SAVE_NAME
	, ATTACH_THUMBNAIL_SIZE
	, ATTACH_THUMBNAIL_LOCATION
	, ATTACH_CONTENTS_ORIGINAL_NAME
	, ATTACH_CONTENTS_SAVE_NAME
	, ATTACH_CONTENTS_SIZE
	, ATTACH_CONTENTS_LOCATION
	, ATTACH_INSERT_DATE
	, ATTACH_DELETE_DATE
	, POST_NUMBER
)
VALUES(
	  CASE WHEN (SELECT MAX(ATTACH_NUMBER) FROM TSHOP.TB_POST_IMAGEFILE) IS NULL THEN 1 ELSE (SELECT MAX(ATTACH_NUMBER) + 1 FROM TSHOP.TB_POST_IMAGEFILE) END
	, '리샘2.jpg'
	, '리뷰샘플2.jpg'
	, 500
	, '/attach/리뷰샘플2.jpg'
	, NULL
	, NULL
	, 0
	, NULL
	, SYSDATE
	, SYSDATE
	, 2
);
INSERT INTO TSHOP.TB_POST_IMAGEFILE(
	  ATTACH_NUMBER
	, ATTACH_THUMBNAIL_ORIGINAL_NAME
	, ATTACH_THUMBNAIL_SAVE_NAME
	, ATTACH_THUMBNAIL_SIZE
	, ATTACH_THUMBNAIL_LOCATION
	, ATTACH_CONTENTS_ORIGINAL_NAME
	, ATTACH_CONTENTS_SAVE_NAME
	, ATTACH_CONTENTS_SIZE
	, ATTACH_CONTENTS_LOCATION
	, ATTACH_INSERT_DATE
	, ATTACH_DELETE_DATE
	, POST_NUMBER
)
VALUES(
	  CASE WHEN (SELECT MAX(ATTACH_NUMBER) FROM TSHOP.TB_POST_IMAGEFILE) IS NULL THEN 1 ELSE (SELECT MAX(ATTACH_NUMBER) + 1 FROM TSHOP.TB_POST_IMAGEFILE) END
	, '리샘3.jpg'
	, '리뷰샘플3.jpg'
	, 500
	, '/attach/리뷰샘플3.jpg'
	, NULL
	, NULL
	, 0
	, NULL
	, SYSDATE
	, SYSDATE
	, 3
);
